version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "calcApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xus8brsbi8jp"
s3_prefix = "calcApp"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
