AWSTemplateFormatVersion: 2010-09-09
Description: Simple calculator app
Transform: AWS::Serverless-2016-10-31
Resources:
  resultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Update BucketName here
      BucketName: "uniqueBucketName"
  calcFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/calc.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function which performs spme calculations
      Policies:
        S3WritePolicy:
          BucketName: !Ref resultsBucket